function Tbl = make_loading_table_bvar1(L)
% A/n plus macro & latent loadings per 1/n
    Tbl = table( ...
        L.nList, L.A_over_n, ...
        L.B_M_over_n(:,1), L.B_M_over_n(:,2), ...
        L.B_L_over_n(:,1), L.B_L_over_n(:,2), L.B_L_over_n(:,3), ...
        'VariableNames', {'nMonths','A_over_n', ...
                          'BM_inf','BM_act','BL_1','BL_2','BL_3'});
end
